import { 
  Cpu, 
  ListTodo, 
  Box, 
  Grid, 
  Settings, 
  Copy, 
  Zap, 
  TrendingUp, 
  Award,
  Flame,
  Globe,
  User,
  Power,
  Wallet,
  ArrowUpRight,
  ArrowDownLeft,
  History,
  CreditCard,
  Twitter,
  Youtube,
  MessageCircle,
  Users,
  Check,
  Gamepad2,
  ChevronRight,
  Calendar,
  ShoppingBag,
  Gem,
  Dices,
  Hammer,
  CircuitBoard,
  Lock
} from 'lucide-react';

export const Icons = {
  Mining: Cpu,
  Task: ListTodo,
  Core: Box,
  More: Grid,
  Settings: Settings,
  Copy: Copy,
  Boost: TrendingUp,
  Rank: Award,
  Energy: Zap,
  Fire: Flame,
  Globe: Globe,
  User: User,
  Power: Power,
  Wallet: Wallet,
  Send: ArrowUpRight,
  Receive: ArrowDownLeft,
  History: History,
  Card: CreditCard,
  Twitter: Twitter,
  Youtube: Youtube,
  Telegram: MessageCircle,
  Users: Users,
  Check: Check,
  Game: Gamepad2,
  ChevronRight: ChevronRight,
  Calendar: Calendar,
  Store: ShoppingBag,
  NFT: Gem,
  Chance: Dices,
  Mint: Hammer,
  Chip: CircuitBoard,
  Lock: Lock
};